### ISSUE TITLE
生产者正常工作

### ISSUE THREAD

**Issue by iamnotgay** [goudai/spring-boot-starter-kafka#2]
@EnableKafka("user-consumer")
public class UserConsumer {

    @KafkaListener(topic = "xxx")
    public void onUserRegisterCouponGranted(ConsumerRecord<String, String> consumerRecord) {
        System.out.println(JsonUtils.toJson(consumerRecord));
    }
}

消费者没有报错，但是没有监听到消息呀

**Comment by goudai** [comment]
贴完整的代码

**Comment by goudai** [comment]
!!
