### ISSUE TITLE
Consumer Processor bug for queue

### ISSUE THREAD

**Issue by zorkelvll** [goudai/spring-boot-starter-kafka#7]
在KafkaBeanPostProcessor.java有个小bug， @PostConstruct public void start()中postconstruct的作用是在postProcessAfterInitialization这个方法执行之前就执行了，这个地方的顺序有问题，导致queue会是空的数组，可以通过继承ApplicationRunner在run方法中调用现有的start方法替代之，烦请确认一下？？？？

**Comment by goudai** [comment]
你说emailQueue吗 不会为null的
